# Generated by Django 4.2.1 on 2023-08-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=255)),
                ('profileUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('edition', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=500)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorOfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.author')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.book')),
            ],
        ),
    ]
