# Generated by Django 4.2.1 on 2023-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorOfBook',
            field=models.ManyToManyField(to='Homepage.author'),
        ),
        migrations.DeleteModel(
            name='AuthorOfBook',
        ),
    ]
