# Generated by Django 4.2.1 on 2023-08-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_book_authorofbook_delete_authorofbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorOfBook',
            new_name='authorsOfBook',
        ),
    ]
