# Generated by Django 4.2.1 on 2023-09-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_booksbought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dateAdded',
        ),
    ]
